### ISSUE TITLE
data format

### ISSUE THREAD

**Issue by Sannndy0000** [Charleo85/pyhtmm#2]
Hi,

Can you specify what is the expected input data format or what data you have used? I am confused by the laptops_bootstrapping_new.dat file. How do I generate that if I'm using my own corpus?

Thank you!

**Comment by Charleo85** [comment]
You can either convert your corpus to our data format:
```
document folder/ 
    doc1.json
        {"ProductInfo": {"Price": null, "Features": null, "Name": null, "ImgURL": null, "ProductID": ""},
"Reviews": [
{"Title": "", "Author": "", "ReviewID": "",  "Overall": "",  "Content": "doc1_texts", "Date": ":},
{"Title": "", "Author": "", "ReviewID": "",  "Overall": "",  "Content": "doc2_texts", "Date": ":}, 
...
],             }
    ...
```
Set each document as the content of each object in the json array. The rest of the metadata shouldn't matter unless you are also working on product reviews.   

or I suggest the more easier and nature way, you can just write your own data-loader, all you need is just first load a word2index map and send each of your document string and word2index map to 'process.process_doc'. 

The 'laptops_bootstrapping_new.dat' is the prior for each word,  which is a list of word seperated by linebreaker that you want to set its phi_ (prior value)

Let me know if you have other questions.

**Comment by Sannndy0000** [comment]
This is very helpful! Thank you!!
